# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25b89937ace9f063b598fcee42c070869b02d2ec5b27478269567826e5d4127b26fdfd18b4b8e5a0cf8a34cc7128fc2fcba0ee44055fc2a38e1f310efde6dddf

test:
  secret_key_base: 461032ba4392aa909395c41243e0cfc8bd8ab73750a8279f545ad3bf664fed83ee8094277de6bacd305ab8b13abf406e5343253115af8575525f2b219223851b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
